version: "3.8"

services:

  configServer:
    image: bbc1/configserver:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - bbc-network

  eurekaServer:
    image: bbc1/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - bbc-network
    depends_on:
      - configServer

  apiGatewayServer:
    image: bbc1/apigatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - bbc-network
    depends_on:
      - configServer
      - eurekaServer
      - controller
  

  controller:
    image: bbc1/controller:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - bbc-network
    depends_on:
      - configServer
      - eurekaServer

#  test_app:
#    image: bbc1/testapp:latest
#    mem_limit: 700m
#    ports:
#      - "8091:8091"
#    networks:
#      - bbc-network
#    depends_on:
#      - configServer
#      - eurekaServer
#      - controller
networks:
  bbc-network: