version: '3'

services:
  apigatewayserver:
    image: bbc1/apigatewayserver:latest
    mem_limit: 700m
    ports:
      - "8073:8072"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  default:
    name: bbc