version: "3.8"
services:
 mongodb:
      image: mongo
      container_name: mongodb
      ports:
       - 27017:27017
      volumes:
       - data:/data
      environment:
       - MONGO_INITDB_ROOT_USERNAME=aliasaddik
       - MONGO_INITDB_ROOT_PASSWORD=CXsNZ56Z9wZETGnu
 mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
       - 8081:8081
    environment:
       - ME_CONFIG_MONGODB_SERVER=mongodb
       - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
       - ME_CONFIG_MONGODB_ADMINUSERNAME=aliasaddik
       - ME_CONFIG_MONGODB_ADMINPASSWORD=CXsNZ56Z9wZETGnu

    depends_on:
      - mongodb
volumes:
  data: {}
networks:
    default:
         name: mongodb_network