services:
  deploymentserver:
    image: bbc1/deploymentserver:latest
    privileged: true
    #  volumes : 
    #    - ./demoapp:/workspace
    mem_limit: 700m
    ports:
      - "8060:8060"
    environment:
      SPRING_PROFILES_ACTIVE: default

networks:
  default:
      name: bbc
